import type { SocialChapter } from "./socialStudiesTopics";

// Grades 1–5 English syllabus: per grade, chapters of [item, icon, description].
// Each item becomes a topic named "Chapter: Item" (see subjectModules.ts), so
// the same skill in different chapters or grades never clashes.

export const ENGLISH_SYLLABUS: Record<number, SocialChapter[]> = {
  1: [
    ["Alphabet and Phonics", [
      ["A to Z", "🔤", "The 26 letters of the alphabet"],
      ["Capital and Small Letters", "🅰️", "A and a, B and b"],
      ["Letter Sounds", "🗣️", "The sound each letter makes"],
      ["Vowels and Consonants", "🔠", "A, E, I, O, U and the rest"],
      ["Beginning Sounds", "▶️", "The first sound in a word"],
      ["Ending Sounds", "⏹️", "The last sound in a word"],
      ["CVC Words", "🐱", "Three-letter words: cat, dog, sun"],
      ["Rhyming Words", "🎵", "Cat, hat, bat — words that sound alike"],
    ]],
    ["Vocabulary", [
      ["Family", "👨‍👩‍👧", "Words for family members"],
      ["Body Parts", "🧍", "Head, hands, eyes and more"],
      ["Colours", "🎨", "Red, blue, yellow and more"],
      ["Shapes", "🔺", "Circle, square, triangle"],
      ["Animals", "🐘", "Names of animals"],
      ["Fruits and Vegetables", "🍎", "Mango, banana, carrot and more"],
      ["Food", "🍚", "Things we eat"],
      ["Clothes", "👕", "Shirt, frock, cap and more"],
      ["School", "🏫", "Words we use at school"],
      ["Home", "🏠", "Rooms and things at home"],
      ["Numbers", "🔢", "One, two, three in words"],
      ["Common Action Words", "🏃", "Run, jump, eat, sleep"],
    ]],
    ["Grammar", [
      ["Naming Words (Nouns)", "🏷️", "Names of people, places and things"],
      ["Pronouns: I, You, He, She, It", "🙋", "Words used in place of names"],
      ["Action Words (Verbs)", "🤸", "Words that show doing"],
      ["Describing Words (Adjectives)", "🌈", "Words that tell how something looks"],
      ["One and Many", "🍎", "One apple, many apples"],
      ["This, That, These, Those", "👉", "Pointing to things near and far"],
      ["A and An", "🅰️", "A cat, an apple"],
      ["Is, Am, Are", "✅", "I am, he is, they are"],
      ["Simple Sentence Formation", "🧱", "Putting words in the right order"],
    ]],
    ["Reading", [
      ["Letter and Word Recognition", "👀", "Finding letters and words"],
      ["Sight Words", "⚡", "the, is, and, to — words to know by sight"],
      ["Simple Sentences", "📝", "Reading short sentences"],
      ["Short Stories", "📖", "Reading little stories"],
      ["Picture-based Reading", "🖼️", "Reading with the help of pictures"],
      ["Basic Comprehension", "❓", "Understanding what we read"],
    ]],
    ["Writing", [
      ["Letter Formation", "✍️", "Writing letters the right way"],
      ["Copying Words", "📋", "Copying words neatly"],
      ["Spelling", "🔡", "Spelling simple words"],
      ["Completing Sentences", "➕", "Filling in the missing word"],
      ["Picture-based Sentences", "🖼️", "Writing about a picture"],
      ["3 to 5 Sentence Paragraphs", "📄", "Writing a few sentences together"],
    ]],
    ["Speaking and Listening", [
      ["Greetings", "👋", "Good morning, hello, thank you"],
      ["Introducing Yourself", "🙋", "My name is…"],
      ["Asking Simple Questions", "❔", "What, where, who"],
      ["Following Instructions", "👂", "Listening and doing"],
      ["Everyday Conversations", "💬", "Talking with friends and family"],
    ]],
  ],
  2: [
    ["Grammar", [
      ["Nouns", "🏷️", "Naming words"],
      ["Common and Proper Nouns", "🏙️", "city and Delhi"],
      ["Singular and Plural", "🍎", "One and many"],
      ["Pronouns", "🙋", "He, she, it, they"],
      ["Verbs", "🤸", "Action words"],
      ["Adjectives", "🌈", "Describing words"],
      ["Articles", "🅰️", "A, an and the"],
      ["Prepositions", "📦", "In, on, under, behind"],
      ["Conjunctions", "🔗", "And, but, or"],
      ["Is, Am, Are", "✅", "Using is, am and are"],
      ["Was and Were", "⏪", "Talking about the past"],
      ["Has and Have", "🎒", "He has, they have"],
      ["Simple Present Tense", "☀️", "Things we do every day"],
      ["Simple Past Tense", "📅", "Things we did yesterday"],
      ["Sentence Types", "❗", "Telling, asking and exclaiming sentences"],
    ]],
    ["Vocabulary", [
      ["Family", "👨‍👩‍👧", "Words for family and relatives"],
      ["School", "🏫", "Words about school"],
      ["Community", "🏘️", "Words about our neighbourhood"],
      ["Nature", "🌳", "Trees, rivers, sky and more"],
      ["Animals", "🐯", "Animals and their young ones"],
      ["Food", "🍲", "Words about food"],
      ["Transport", "🚌", "Bus, train, boat, aeroplane"],
      ["Occupations", "🧑‍⚕️", "Doctor, farmer, teacher"],
      ["Feelings", "😊", "Happy, sad, angry, scared"],
      ["Opposites", "↔️", "Big and small, hot and cold"],
      ["Synonyms", "🟰", "Words with the same meaning"],
      ["Antonyms", "🔁", "Words with opposite meanings"],
    ]],
    ["Reading", [
      ["Short Stories", "📖", "Reading stories"],
      ["Poems", "🎵", "Reading and enjoying poems"],
      ["Dialogues", "💬", "Reading conversations"],
      ["Reading Comprehension", "❓", "Understanding a passage"],
      ["Main Idea", "💡", "What the passage is mostly about"],
      ["Answering Questions", "✋", "Finding answers in the text"],
      ["Sequencing Events", "🔢", "What happened first, next and last"],
    ]],
    ["Writing", [
      ["Sentences", "📝", "Writing good sentences"],
      ["Short Paragraphs", "📄", "Writing a few sentences together"],
      ["Picture Description", "🖼️", "Writing about a picture"],
      ["Personal Information", "🪪", "Name, age, address"],
      ["Simple Letter", "✉️", "Writing a short letter"],
      ["Story Completion", "📚", "Finishing a story"],
      ["Guided Writing", "🧭", "Writing with hints"],
    ]],
    ["Speaking", [
      ["Self-introduction", "🙋", "Telling others about yourself"],
      ["Describing People and Objects", "🔍", "Saying what someone or something is like"],
      ["Asking and Answering Questions", "❔", "Questions and replies"],
      ["Role-play", "🎭", "Acting out everyday scenes"],
      ["Everyday Conversations", "💬", "Talking politely"],
    ]],
  ],
  3: [
    ["Grammar", [
      ["Nouns", "🏷️", "Kinds of naming words"],
      ["Pronouns", "🙋", "Words in place of nouns"],
      ["Verbs", "🤸", "Action words"],
      ["Adjectives", "🌈", "Describing words"],
      ["Adverbs", "🐢", "Words that tell how, when, where"],
      ["Articles", "🅰️", "A, an and the"],
      ["Prepositions", "📦", "Words that show position"],
      ["Conjunctions", "🔗", "Joining words"],
      ["Singular and Plural", "🍎", "One and many"],
      ["Subject and Predicate", "🧩", "The two parts of a sentence"],
      ["Simple Present", "☀️", "Everyday actions"],
      ["Simple Past", "📅", "Actions that are over"],
      ["Simple Future", "🔮", "Actions that will happen"],
      ["Present Continuous", "🏃", "Actions happening now"],
      ["Question Words", "❓", "Who, what, where, when, why, how"],
      ["Punctuation", "❗", "Full stop, comma, question mark"],
      ["Capitalization", "🔠", "When to use capital letters"],
    ]],
    ["Vocabulary", [
      ["Synonyms", "🟰", "Words with the same meaning"],
      ["Antonyms", "🔁", "Words with opposite meanings"],
      ["Homophones", "👂", "Sound the same, spelt differently: sea, see"],
      ["Compound Words", "🧱", "Sun + flower = sunflower"],
      ["Prefixes", "⬅️", "un-, re- at the start of words"],
      ["Suffixes", "➡️", "-ful, -less at the end of words"],
      ["Word Families", "👪", "-at words: cat, bat, mat"],
      ["Contextual Vocabulary", "🔎", "Guessing meaning from the sentence"],
      ["Dictionary Skills", "📕", "Alphabetical order and finding words"],
    ]],
    ["Reading", [
      ["Stories", "📖", "Reading stories"],
      ["Poems", "🎵", "Reading poems"],
      ["Fables", "🦊", "Stories with a moral"],
      ["Informational Passages", "📰", "Reading to learn facts"],
      ["Main Idea", "💡", "What the passage is about"],
      ["Supporting Details", "📌", "Facts that explain the main idea"],
      ["Character Identification", "🧒", "Who is in the story"],
      ["Sequence of Events", "🔢", "Order of what happened"],
      ["Making Simple Inferences", "🕵️", "Reading between the lines"],
      ["Vocabulary from Context", "🔎", "Working out word meanings"],
    ]],
    ["Writing", [
      ["Paragraph Writing", "📄", "Writing a paragraph"],
      ["Story Writing", "📚", "Writing a story"],
      ["Picture Composition", "🖼️", "Writing about a picture"],
      ["Informal Letters", "✉️", "Letters to family and friends"],
      ["Diary Entry", "📔", "Writing about your day"],
      ["Descriptive Writing", "🌄", "Describing people and places"],
      ["Creative Writing", "✨", "Writing from your imagination"],
      ["Summarizing Short Passages", "✂️", "Saying it in fewer words"],
    ]],
    ["Speaking and Listening", [
      ["Conversations", "💬", "Talking with others"],
      ["Storytelling", "🧚", "Telling a story aloud"],
      ["Describing Events", "🎉", "Telling what happened"],
      ["Giving Instructions", "📋", "Telling someone how to do something"],
      ["Asking Questions", "❔", "Asking politely"],
      ["Listening Comprehension", "👂", "Understanding what we hear"],
      ["Role-play", "🎭", "Acting out conversations"],
    ]],
  ],
  4: [
    ["Grammar", [
      ["Common and Proper Nouns", "🏙️", "General and special names"],
      ["Collective Nouns", "🐝", "A swarm of bees, a herd of cows"],
      ["Abstract Nouns", "💭", "Love, honesty, courage"],
      ["Pronouns", "🙋", "Words in place of nouns"],
      ["Possessive Pronouns", "🎒", "Mine, yours, his, hers"],
      ["Verbs", "🤸", "Action words"],
      ["Helping Verbs", "🤝", "Is, has, can, will"],
      ["Adjectives", "🌈", "Describing words"],
      ["Degrees of Comparison", "📏", "Tall, taller, tallest"],
      ["Adverbs", "🐢", "How, when and where"],
      ["Prepositions", "📦", "In, on, between, across"],
      ["Conjunctions", "🔗", "And, but, because, so"],
      ["Articles", "🅰️", "A, an and the"],
      ["Subject-Verb Agreement", "⚖️", "He plays, they play"],
      ["Simple, Continuous and Perfect Tenses", "⏳", "Plays, is playing, has played"],
      ["Direct Speech", "🗨️", "Writing what someone said"],
      ["Punctuation", "❗", "Commas, quotation marks and more"],
      ["Sentence Types", "❓", "Statements, questions, commands, exclamations"],
    ]],
    ["Vocabulary", [
      ["Synonyms and Antonyms", "🔁", "Same and opposite meanings"],
      ["Homophones", "👂", "Sound alike, mean different things"],
      ["Homonyms", "🦇", "Same word, different meanings: bat"],
      ["Prefixes", "⬅️", "Word beginnings that change meaning"],
      ["Suffixes", "➡️", "Word endings that change meaning"],
      ["Compound Words", "🧱", "Two words joined into one"],
      ["Idioms", "🐱", "Phrases like 'a piece of cake'"],
      ["Proverbs", "🦉", "Wise sayings"],
      ["Context Clues", "🔎", "Using nearby words to find meaning"],
      ["Dictionary and Thesaurus Skills", "📕", "Finding meanings and synonyms"],
    ]],
    ["Reading", [
      ["Fiction", "🧚", "Made-up stories"],
      ["Non-fiction", "📰", "True information"],
      ["Poems", "🎵", "Reading poetry"],
      ["Biographies", "👤", "Stories of real people's lives"],
      ["Informational Texts", "📊", "Texts that teach facts"],
      ["Main Idea", "💡", "The big idea of a text"],
      ["Supporting Details", "📌", "Details that back up the main idea"],
      ["Inference", "🕵️", "Working out what is not said"],
      ["Cause and Effect", "➡️", "Why something happened"],
      ["Compare and Contrast", "⚖️", "How things are alike and different"],
      ["Fact vs Opinion", "✅", "What is true and what someone thinks"],
      ["Summarizing", "✂️", "Saying the main points briefly"],
    ]],
    ["Writing", [
      ["Paragraph Writing", "📄", "Writing a good paragraph"],
      ["Descriptive Writing", "🌄", "Painting a picture with words"],
      ["Narrative Writing", "📚", "Telling a story in order"],
      ["Informal Letters", "✉️", "Letters to friends and family"],
      ["Formal Letters", "📨", "An introduction to formal letters"],
      ["Diary Writing", "📔", "Writing a diary entry"],
      ["Story Writing", "🐉", "Writing your own story"],
      ["Essay Writing", "📝", "Writing an essay"],
      ["Picture Composition", "🖼️", "Writing about a picture"],
      ["Summaries", "✂️", "Writing a summary"],
    ]],
    ["Speaking", [
      ["Presentations", "🎤", "Speaking in front of the class"],
      ["Storytelling", "🧚", "Telling stories aloud"],
      ["Group Discussions", "👥", "Sharing ideas in a group"],
      ["Describing Experiences", "🏞️", "Talking about what happened"],
      ["Giving Opinions", "👍", "Saying what you think and why"],
      ["Role-play", "🎭", "Acting out situations"],
      ["Public Speaking Basics", "📢", "Speaking clearly and confidently"],
    ]],
  ],
  5: [
    ["Parts of Speech", [
      ["Nouns", "🏷️", "All kinds of nouns"],
      ["Pronouns", "🙋", "Personal, possessive and more"],
      ["Verbs", "🤸", "Action and helping verbs"],
      ["Adjectives", "🌈", "Describing words"],
      ["Adverbs", "🐢", "Words that describe verbs"],
      ["Prepositions", "📦", "Words of position and direction"],
      ["Conjunctions", "🔗", "Joining words and sentences"],
      ["Interjections", "😲", "Wow! Oh! Hurray!"],
      ["Articles", "🅰️", "A, an and the"],
    ]],
    ["Tenses", [
      ["Simple Present", "☀️", "Habits and facts"],
      ["Present Continuous", "🏃", "Actions happening now"],
      ["Present Perfect", "✅", "Has done, have finished"],
      ["Simple Past", "📅", "Finished actions"],
      ["Past Continuous", "⏪", "Was doing, were playing"],
      ["Past Perfect", "⏮️", "An introduction to had done"],
      ["Simple Future", "🔮", "Will do"],
      ["Future Continuous", "🚀", "An introduction to will be doing"],
    ]],
    ["Sentence Structure", [
      ["Subject and Predicate", "🧩", "The two parts of a sentence"],
      ["Simple Sentences", "📝", "One main idea"],
      ["Compound Sentences", "🔗", "Two ideas joined by and, but, or"],
      ["Complex Sentences", "🧠", "An introduction to because, when, although"],
      ["Clauses", "🧱", "Main and dependent clauses"],
      ["Subject-Verb Agreement", "⚖️", "Matching subjects and verbs"],
      ["Active and Passive Voice", "🔄", "An introduction to who does the action"],
      ["Direct and Indirect Speech", "🗨️", "An introduction to reporting speech"],
    ]],
    ["Other Grammar", [
      ["Degrees of Comparison", "📏", "Positive, comparative, superlative"],
      ["Modals", "🛑", "Can, could, may, must, should"],
      ["Question Tags", "❓", "It's hot, isn't it?"],
      ["Punctuation", "❗", "All the punctuation marks"],
      ["Capitalization", "🔠", "Capital letter rules"],
      ["Editing and Error Correction", "🖍️", "Finding and fixing mistakes"],
    ]],
    ["Vocabulary", [
      ["Synonyms", "🟰", "Words with the same meaning"],
      ["Antonyms", "🔁", "Words with opposite meanings"],
      ["Homophones", "👂", "Sound alike, spelt differently"],
      ["Homonyms", "🦇", "Same word, different meanings"],
      ["Prefixes", "⬅️", "Word beginnings"],
      ["Suffixes", "➡️", "Word endings"],
      ["Root Words", "🌱", "The base of a word"],
      ["Compound Words", "🧱", "Words made of two words"],
      ["Idioms", "🐱", "Phrases with a special meaning"],
      ["Proverbs", "🦉", "Wise old sayings"],
      ["Multiple-meaning Words", "🔀", "Words with more than one meaning"],
      ["Contextual Vocabulary", "🔎", "Meaning from the sentence"],
    ]],
    ["Reading", [
      ["Fiction", "🧚", "Stories from imagination"],
      ["Non-fiction", "📰", "Factual writing"],
      ["Poetry", "🎵", "Poems and their meaning"],
      ["Biographies", "👤", "Lives of real people"],
      ["News and Informational Passages", "🗞️", "Reading news and facts"],
      ["Main Idea", "💡", "The central idea"],
      ["Supporting Details", "📌", "Details that support the main idea"],
      ["Inference", "🕵️", "Drawing conclusions"],
      ["Prediction", "🔮", "Guessing what happens next"],
      ["Cause and Effect", "➡️", "Why and what happened"],
      ["Compare and Contrast", "⚖️", "Alike and different"],
      ["Fact and Opinion", "✅", "True facts and personal views"],
      ["Author's Purpose", "✍️", "Why the author wrote it"],
      ["Vocabulary in Context", "🔎", "Meaning from the passage"],
      ["Summarization", "✂️", "The main points in brief"],
    ]],
    ["Writing", [
      ["Paragraph Writing", "📄", "Well-organised paragraphs"],
      ["Essay Writing", "📝", "Introduction, body and conclusion"],
      ["Story Writing", "🐉", "Beginning, middle and end"],
      ["Creative Writing", "✨", "Writing from imagination"],
      ["Descriptive Writing", "🌄", "Using the five senses"],
      ["Narrative Writing", "📚", "Telling events in order"],
      ["Informal Letters", "✉️", "Letters to people we know"],
      ["Formal Letters", "📨", "Letters to the principal, editor and others"],
      ["Emails", "📧", "Writing a clear email"],
      ["Diary Entries", "📔", "Writing about your day"],
      ["Reports", "📋", "A basic report"],
      ["Summaries", "✂️", "Writing a summary"],
      ["Picture Composition", "🖼️", "Writing about a picture"],
    ]],
    ["Speaking and Listening", [
      ["Self-introduction", "🙋", "Introducing yourself confidently"],
      ["Conversations", "💬", "Polite conversations"],
      ["Storytelling", "🧚", "Telling stories well"],
      ["Presentations", "🎤", "Presenting to an audience"],
      ["Group Discussions", "👥", "Discussing in a group"],
      ["Asking and Answering Questions", "❔", "Clear questions and answers"],
      ["Giving Instructions", "📋", "Step-by-step instructions"],
      ["Expressing Opinions", "👍", "Giving your view with reasons"],
      ["Describing Pictures and Events", "🖼️", "Describing what you see"],
      ["Listening Comprehension", "👂", "Understanding what you hear"],
      ["Pronunciation", "🗣️", "Saying words correctly"],
      ["Fluency", "🌊", "Speaking smoothly"],
    ]],
  ],
};
