import type { SocialChapter } from "./socialStudiesTopics";

// Grades 1–5 General Knowledge syllabus: per grade, chapters of [item, icon, description].
// Each item becomes a topic named "Chapter: Item" (see subjectModules.ts).

// Grades 3–5 also cover current affairs.
const CURRENT_AFFAIRS: SocialChapter = ["Current Affairs", [
  ["Important National Events", "📰", "Big events in India"],
  ["Important International Events", "🌐", "Big events around the world"],
  ["Science Discoveries", "🔭", "New discoveries in science"],
  ["Sports Events", "🏟️", "Recent sports events"],
  ["Awards", "🏆", "Recent awards and winners"],
  ["Government Initiatives", "🏛️", "Schemes and missions of the government"],
  ["Environment", "🌿", "News about our planet"],
  ["Important People and Achievements", "🌟", "People who made us proud"],
]];

export const GK_SYLLABUS: Record<number, SocialChapter[]> = {
  1: [
    ["Myself and Family", [
      ["My Name, Age and Birthday", "🎂", "Telling others about me"],
      ["Family Members", "👨‍👩‍👧", "The people in my family"],
      ["Body Parts", "🧍", "Parts of our body"],
      ["Good Habits", "🙏", "Kind and polite habits"],
      ["Healthy Habits", "🪥", "Habits that keep us healthy"],
    ]],
    ["Animals", [
      ["Domestic Animals", "🐄", "Animals that live with us"],
      ["Wild Animals", "🦁", "Animals of the forest"],
      ["Birds", "🦜", "Birds around us"],
      ["Insects", "🐞", "Small creatures with six legs"],
      ["Sea Animals", "🐬", "Animals that live in the sea"],
      ["Animal Sounds", "🐶", "Moo, bark, roar and more"],
      ["Animal Homes", "🏠", "Nest, den, kennel and more"],
      ["Baby Animals", "🐣", "Calf, puppy, kitten and more"],
    ]],
    ["Plants and Nature", [
      ["Common Plants", "🌱", "Plants we see every day"],
      ["Flowers", "🌸", "Rose, lotus, sunflower"],
      ["Fruits", "🍎", "Mango, apple, banana"],
      ["Vegetables", "🥕", "Carrot, potato, tomato"],
      ["Trees", "🌳", "Neem, banyan, coconut"],
      ["Seasons", "🍂", "Summer, rainy, winter"],
      ["Weather", "🌦️", "Sunny, rainy, windy, cloudy"],
    ]],
    ["Colours, Shapes and Numbers", [
      ["Basic Colours", "🎨", "Red, blue, yellow and more"],
      ["Shapes", "🔺", "Circle, square, triangle"],
      ["Counting", "🔢", "Counting things around us"],
      ["Ordinal Numbers", "🥇", "First, second, third"],
      ["Patterns", "🔁", "What comes next?"],
    ]],
    ["My Surroundings", [
      ["Home", "🏡", "Rooms and things at home"],
      ["School", "🏫", "Places in my school"],
      ["Neighbourhood", "🏘️", "Places near my home"],
      ["Community Helpers", "🧑‍🚒", "People who help us"],
      ["Places Around Us", "🗺️", "Market, park, hospital"],
    ]],
    ["Transport and Communication", [
      ["Road Transport", "🚌", "Cars, buses and bicycles"],
      ["Railways", "🚆", "Trains and stations"],
      ["Air Transport", "✈️", "Aeroplanes and helicopters"],
      ["Water Transport", "⛵", "Boats and ships"],
      ["Telephone", "☎️", "Talking to people far away"],
      ["Internet", "💻", "A basic idea of the internet"],
    ]],
    ["India", [
      ["Name of Our Country", "🗺️", "Our country, India"],
      ["National Flag", "🏳️", "The tricolour"],
      ["National Animal", "🐅", "The tiger"],
      ["National Bird", "🦚", "The peacock"],
      ["National Flower", "🪷", "The lotus"],
      ["National Fruit", "🥭", "The mango"],
      ["National Anthem", "🎶", "Jana Gana Mana"],
    ]],
    ["Important Days", [
      ["Independence Day", "🎆", "15 August"],
      ["Republic Day", "🎖️", "26 January"],
      ["Children's Day", "🧒", "14 November"],
      ["Teachers' Day", "👩‍🏫", "5 September"],
      ["Gandhi Jayanti", "🕊️", "2 October"],
      ["World Environment Day", "🌍", "5 June"],
    ]],
  ],
  2: [
    ["India", [
      ["States and Union Territories", "🗺️", "An introduction to India's states and UTs"],
      ["Capitals", "🏛️", "Capitals of some states"],
      ["National Symbols", "🦚", "India's national symbols"],
      ["Indian Currency", "💵", "Rupees, coins and notes"],
      ["Major Cities", "🏙️", "Delhi, Mumbai, Chennai and more"],
      ["Famous Places", "🕌", "Taj Mahal, Red Fort and more"],
    ]],
    ["Famous People", [
      ["Mahatma Gandhi", "🕊️", "The Father of the Nation"],
      ["Jawaharlal Nehru", "🌹", "India's first Prime Minister"],
      ["Dr. B. R. Ambedkar", "📜", "Maker of our Constitution"],
      ["APJ Abdul Kalam", "🚀", "The Missile Man of India"],
      ["Rani Lakshmibai", "⚔️", "The brave queen of Jhansi"],
      ["Subhas Chandra Bose", "🎖️", "Netaji"],
    ]],
    ["Animals and Birds", [
      ["Endangered Animals", "🐼", "Animals we must protect"],
      ["National Animals of Countries", "🦘", "Kangaroo, panda, bald eagle"],
      ["Animal Habitats", "🏞️", "Forests, deserts, oceans"],
      ["Interesting Animal Facts", "🐘", "Amazing things animals do"],
    ]],
    ["Science Around Us", [
      ["Human Body", "🫀", "Our body and its parts"],
      ["Five Senses", "👀", "See, hear, smell, taste, touch"],
      ["Solar System", "🪐", "The Sun and its planets"],
      ["Water", "💧", "Why water is precious"],
      ["Air", "🌬️", "Air all around us"],
      ["Light", "💡", "Sources of light"],
      ["Sound", "🔊", "Loud and soft sounds"],
    ]],
    ["Sports", [
      ["Popular Sports", "⚽", "Cricket, football, kabaddi"],
      ["Sports Equipment", "🏏", "Bat, ball, racket, net"],
      ["Famous Indian Sportspersons", "🏅", "Sachin, Mary Kom, Neeraj Chopra and more"],
      ["Major Sports Events", "🏟️", "Olympics and World Cups"],
    ]],
    ["Geography", [
      ["Continents", "🌍", "The seven continents"],
      ["Oceans", "🌊", "The five oceans"],
      ["Mountains", "🏔️", "The Himalayas and more"],
      ["Rivers", "🏞️", "Ganga, Nile and more"],
      ["Deserts", "🐪", "Thar and Sahara"],
    ]],
    ["Festivals and Culture", [
      ["Indian Festivals", "🪔", "Diwali, Eid, Christmas, Pongal"],
      ["Traditional Dances", "💃", "Dances of India"],
      ["Music", "🎵", "Songs and instruments"],
      ["Languages", "🗣️", "Languages of India"],
      ["Traditional Clothes and Food", "🥻", "What we wear and eat"],
    ]],
    ["Important Days", [
      ["National and International Days", "📅", "Days we celebrate"],
      ["Why We Celebrate Them", "🎉", "The reasons behind special days"],
    ]],
  ],
  3: [
    ["Indian Geography", [
      ["States and Capitals", "🏛️", "India's states and their capitals"],
      ["Union Territories", "🗺️", "India's Union Territories"],
      ["Major Rivers", "🌊", "Ganga, Yamuna, Godavari, Krishna"],
      ["Mountains", "🏔️", "Himalayas, Western and Eastern Ghats"],
      ["Lakes", "🛶", "Dal, Chilika, Wular and more"],
      ["Deserts", "🐪", "The Thar Desert"],
      ["Seas and Oceans", "🌊", "Arabian Sea, Bay of Bengal, Indian Ocean"],
      ["Neighbouring Countries", "🤝", "Countries next to India"],
    ]],
    ["World Geography", [
      ["Continents", "🌍", "The seven continents"],
      ["Oceans", "🐋", "The five oceans"],
      ["Countries", "🗺️", "Countries of the world"],
      ["Capitals", "🏛️", "Capitals of countries"],
      ["Famous Landmarks", "🗼", "Eiffel Tower, Great Wall and more"],
      ["Major Rivers and Mountains", "⛰️", "Nile, Amazon, Everest"],
    ]],
    ["Indian History", [
      ["Ancient India", "📜", "An introduction to ancient India"],
      ["Famous Kings and Rulers", "👑", "Ashoka, Akbar, Shivaji and more"],
      ["Freedom Fighters", "✊", "Heroes of our freedom struggle"],
      ["Indian Independence", "🎆", "15 August 1947"],
      ["Important Historical Places", "🏰", "Forts, temples and monuments"],
    ]],
    ["Indian Government", [
      ["President", "🎖️", "The head of our country"],
      ["Prime Minister", "🧑‍💼", "The head of the government"],
      ["Parliament", "🏛️", "Where laws are made"],
      ["State Governments", "🏢", "How states are run"],
      ["Elections", "🗳️", "How we choose leaders"],
      ["Constitution", "📜", "Our country's rule book"],
    ]],
    ["Science GK", [
      ["Solar System", "☀️", "The Sun and its family"],
      ["Planets", "🪐", "The eight planets"],
      ["Human Body", "🫀", "Organs and what they do"],
      ["Animals", "🐾", "Amazing animal facts"],
      ["Plants", "🌿", "Amazing plant facts"],
      ["Inventions", "💡", "The bulb, the telephone and more"],
      ["Discoveries", "🔬", "Great discoveries in science"],
    ]],
    ["Sports GK", [
      ["Cricket", "🏏", "Rules and famous players"],
      ["Football", "⚽", "The world's most popular game"],
      ["Hockey", "🏑", "India's hockey history"],
      ["Tennis", "🎾", "Grand Slams and players"],
      ["Badminton", "🏸", "Shuttle stars of India"],
      ["Olympics", "🏅", "The biggest sports event"],
      ["Famous Sportspersons", "🌟", "Sports heroes"],
    ]],
    ["Books and Authors", [
      ["Famous Children's Books", "📚", "Panchatantra, Malgudi Days and more"],
      ["Famous Indian Authors", "✍️", "Ruskin Bond, R. K. Narayan, Tagore"],
      ["Famous Characters", "🧙", "Tenali Raman, Swami and more"],
    ]],
    ["Art and Culture", [
      ["Indian Dances", "💃", "Bharatanatyam, Kathak, Kuchipudi"],
      ["Musical Instruments", "🎻", "Sitar, tabla, veena, flute"],
      ["Paintings", "🎨", "Madhubani, Warli and more"],
      ["Monuments", "🕌", "Famous monuments of India"],
      ["Festivals", "🪔", "Festivals of India"],
    ]],
    CURRENT_AFFAIRS,
  ],
  4: [
    ["India", [
      ["States and Capitals", "🏛️", "All states and capitals"],
      ["Union Territories", "🗺️", "UTs and their capitals"],
      ["Major Cities", "🏙️", "Important cities of India"],
      ["Rivers and Dams", "🌊", "Rivers and the dams built on them"],
      ["National Parks", "🐅", "Jim Corbett, Kaziranga and more"],
      ["Wildlife Sanctuaries", "🦌", "Places that protect wildlife"],
      ["Important Monuments", "🕌", "Monuments and where they are"],
      ["UNESCO Heritage Sites", "🏛️", "An introduction to world heritage sites in India"],
    ]],
    ["World", [
      ["Countries and Capitals", "🌐", "Countries and their capitals"],
      ["Continents", "🌍", "Facts about the continents"],
      ["Oceans", "🐋", "Facts about the oceans"],
      ["Major Landmarks", "🗽", "Famous landmarks of the world"],
      ["Important Rivers", "🏞️", "Great rivers of the world"],
      ["Mountains", "🏔️", "Highest mountains of the world"],
      ["Deserts", "🐪", "Largest deserts of the world"],
      ["Time Zones", "🕒", "A basic idea of time zones"],
    ]],
    ["Indian History", [
      ["Indus Valley Civilization", "🏺", "Harappa and Mohenjo-daro"],
      ["Mauryan Empire", "🦁", "Chandragupta and Ashoka"],
      ["Gupta Empire", "✨", "The golden age"],
      ["Medieval India", "🏰", "Kingdoms of medieval India"],
      ["Mughal Period", "👑", "The Mughals"],
      ["British Rule", "⛓️", "How the British ruled India"],
      ["Freedom Movement", "✊", "India's fight for freedom"],
    ]],
    ["Civics and Government", [
      ["Constitution", "📜", "Our Constitution"],
      ["President", "🎖️", "The President of India"],
      ["Prime Minister", "🧑‍💼", "The Prime Minister of India"],
      ["Parliament", "🏛️", "Lok Sabha and Rajya Sabha"],
      ["Supreme Court", "⚖️", "The highest court of India"],
      ["State Government", "🏢", "Governor and Chief Minister"],
      ["Local Government", "🏘️", "Panchayats and municipalities"],
      ["Fundamental Rights", "✅", "A basic idea of our rights"],
    ]],
    ["Science and Technology", [
      ["Human Body", "🫀", "Body systems and facts"],
      ["Solar System", "🪐", "Planets, moons and stars"],
      ["Physics in Everyday Life", "⚙️", "Science we use every day"],
      ["Chemistry Around Us", "🧪", "Science in the kitchen and home"],
      ["Inventions", "💡", "Great inventions and inventors"],
      ["Scientists", "👩‍🔬", "Famous scientists"],
      ["Computers", "💻", "Parts and uses of computers"],
      ["Internet", "🌐", "How the internet connects us"],
      ["Artificial Intelligence", "🤖", "A basic idea of AI"],
    ]],
    ["Environment", [
      ["Pollution", "🏭", "Air, water and land pollution"],
      ["Climate", "🌡️", "Climates of the world"],
      ["Global Warming", "🔥", "Why the Earth is getting warmer"],
      ["Renewable Energy", "☀️", "Sun, wind and water power"],
      ["Conservation", "♻️", "Saving nature"],
      ["Endangered Species", "🐼", "Animals in danger"],
      ["Recycling", "🔄", "Reduce, reuse, recycle"],
    ]],
    ["Sports", [
      ["Olympics", "🏅", "The Olympic Games"],
      ["Cricket World Cup", "🏏", "The cricket World Cup"],
      ["FIFA World Cup", "⚽", "The football World Cup"],
      ["Asian Games", "🥇", "Asia's biggest sports event"],
      ["Commonwealth Games", "🏟️", "Games of Commonwealth nations"],
      ["Famous Athletes", "🏃", "Sports stars of India and the world"],
    ]],
    ["Awards and Achievements", [
      ["Nobel Prize", "🏅", "The world's famous prize"],
      ["Bharat Ratna", "🎖️", "India's highest civilian award"],
      ["Padma Awards", "🪷", "Padma Vibhushan, Bhushan and Shri"],
      ["Major Sports Awards", "🏆", "Khel Ratna, Arjuna Award"],
      ["Famous Achievements by Indians", "🌟", "Indians who made history"],
    ]],
    CURRENT_AFFAIRS,
  ],
  5: [
    ["Indian GK", [
      ["States and Capitals", "🏛️", "States, capitals and facts"],
      ["Union Territories", "🗺️", "UTs and their capitals"],
      ["Important Cities", "🏙️", "Cities and what they are known for"],
      ["Rivers", "🌊", "Rivers of India"],
      ["Dams", "🚧", "Major dams of India"],
      ["Mountains", "🏔️", "Mountain ranges and peaks"],
      ["National Parks", "🐅", "National parks and their animals"],
      ["Wildlife Sanctuaries", "🦌", "Sanctuaries of India"],
      ["Monuments", "🕌", "Monuments and their builders"],
      ["Heritage Sites", "🏛️", "UNESCO heritage sites in India"],
    ]],
    ["World GK", [
      ["Countries and Capitals", "🌐", "Countries and capitals"],
      ["Currencies", "💱", "Currencies of the world"],
      ["Continents", "🌍", "Facts about continents"],
      ["Oceans", "🐋", "Facts about oceans"],
      ["Major Landmarks", "🗽", "Landmarks of the world"],
      ["Important International Organizations", "🤝", "UN, WHO, UNESCO and more"],
      ["World Records", "📏", "The biggest, tallest, longest"],
    ]],
    ["Indian History", [
      ["Ancient Civilizations", "🏺", "Early civilizations of India"],
      ["Major Dynasties", "👑", "Mauryas, Guptas, Cholas and more"],
      ["Medieval India", "🏰", "Medieval kingdoms"],
      ["Mughal Empire", "🕌", "Babur to Aurangzeb"],
      ["British Rule", "⛓️", "The British in India"],
      ["Freedom Movement", "✊", "The struggle for freedom"],
      ["Important Freedom Fighters", "🕊️", "Heroes of the freedom struggle"],
      ["Independence and Republic", "🎆", "1947 and 1950"],
    ]],
    ["Indian Constitution and Government", [
      ["Constitution", "📜", "Making of our Constitution"],
      ["Fundamental Rights", "⚖️", "Rights of every citizen"],
      ["Fundamental Duties", "✅", "Duties of every citizen"],
      ["President", "🎖️", "Powers of the President"],
      ["Prime Minister", "🧑‍💼", "Role of the Prime Minister"],
      ["Parliament", "🏛️", "How Parliament works"],
      ["Supreme Court", "⚖️", "The highest court"],
      ["State Government", "🏢", "How states are governed"],
      ["Panchayati Raj", "🏘️", "Village self-government"],
      ["Elections", "🗳️", "The Election Commission and voting"],
    ]],
    ["Science and Technology", [
      ["Human Body", "🫀", "Body systems"],
      ["Space", "🚀", "Space missions, ISRO and NASA"],
      ["Solar System", "🪐", "Planets, moons and more"],
      ["Physics", "⚙️", "Force, energy, light and sound"],
      ["Chemistry", "🧪", "Matter and materials"],
      ["Biology", "🧬", "Living things"],
      ["Famous Scientists", "👩‍🔬", "Scientists who changed the world"],
      ["Inventions", "💡", "Inventions and inventors"],
      ["Computers", "💻", "Hardware and software"],
      ["Internet", "🌐", "The internet and staying safe online"],
      ["AI and Robotics", "🤖", "Smart machines"],
    ]],
    ["Environment", [
      ["Ecosystems", "🏞️", "Living things and their surroundings"],
      ["Biodiversity", "🦜", "The variety of life"],
      ["Climate Change", "🌡️", "Changes in Earth's climate"],
      ["Global Warming", "🔥", "Causes and effects"],
      ["Pollution", "🏭", "Kinds of pollution"],
      ["Renewable Energy", "☀️", "Clean energy sources"],
      ["Conservation", "♻️", "Protecting nature"],
      ["Sustainable Development", "🌱", "Growing without harming the planet"],
    ]],
    ["Sports", [
      ["Olympics", "🏅", "The Olympic Games"],
      ["World Cups", "🏆", "World Cups of different sports"],
      ["Asian Games", "🥇", "The Asian Games"],
      ["Famous Athletes", "🏃", "Great athletes"],
      ["Famous Records", "📏", "Sports records"],
      ["Sports Terminology", "📖", "Words used in sports"],
    ]],
    ["Literature and Arts", [
      ["Famous Authors", "✍️", "Great writers"],
      ["Books", "📚", "Famous books"],
      ["Poems", "🎵", "Famous poems and poets"],
      ["Indian Classical Dances", "💃", "The classical dances of India"],
      ["Musical Instruments", "🎻", "Instruments and famous players"],
      ["Famous Paintings", "🖼️", "Paintings the world knows"],
      ["Artists", "🎨", "Famous artists"],
    ]],
    ["Business and Economy", [
      ["Money and Currency", "💵", "Money and how it works"],
      ["Banks", "🏦", "What banks do"],
      ["Savings", "🐷", "Why we save money"],
      ["Taxes", "🧾", "A basic idea of taxes"],
      ["Imports and Exports", "🚢", "Buying and selling with other countries"],
      ["Major Industries", "🏭", "Industries of India"],
      ["Famous Companies", "🏢", "Well-known Indian companies"],
    ]],
    CURRENT_AFFAIRS,
  ],
};
