// Grades 1–5 Social Studies syllabus: per grade, chapters of [item, icon, description].
// Each item becomes a topic named "Chapter: Item" (see subjectModules.ts), so
// names like "Seasons" or "Soil" never clash with the Science topics.

export type SocialChapter = [chapter: string, items: Array<[item: string, icon: string, description: string]>];

export const SOCIAL_SYLLABUS: Record<number, SocialChapter[]> = {
  1: [
    ["Myself", [
      ["My Name, Age and Interests", "🙋", "Telling others about me"],
      ["My Body", "🧍", "Parts of my body and what they do"],
      ["My Likes and Dislikes", "❤️", "Things I enjoy and don't enjoy"],
      ["Good Habits", "🪥", "Habits that keep me healthy and happy"],
    ]],
    ["My Family", [
      ["Family Members", "👨‍👩‍👧‍👦", "The people in my family"],
      ["Types of Families", "🏡", "Small families and joint families"],
      ["Family Relationships", "🤝", "Grandparents, uncles, aunts and cousins"],
      ["Helping Family Members", "🧺", "Small jobs I can do at home"],
    ]],
    ["My Home", [
      ["Different Types of Homes", "🛖", "Huts, flats, houseboats and more"],
      ["Rooms in a House", "🛋️", "Kitchen, bedroom, bathroom and more"],
      ["Keeping the Home Clean", "🧹", "Sweeping, tidying and throwing waste"],
      ["Safety at Home", "⚠️", "Fire, sharp things and electricity"],
    ]],
    ["My School", [
      ["School and Classroom", "🏫", "Places in my school"],
      ["Teachers and Students", "🧑‍🏫", "People who learn together"],
      ["School Rules", "📏", "Rules that help us learn"],
      ["School Helpers", "🧑‍🔧", "Peon, gardener, guard and driver"],
    ]],
    ["My Neighbourhood", [
      ["Neighbours", "🏘️", "People who live near us"],
      ["Places Around Us", "🗺️", "Places near my home"],
      ["Shops", "🏪", "Where we buy things we need"],
      ["Hospitals", "🏥", "Where sick people get better"],
      ["Parks", "🌳", "Places to play and relax"],
      ["Police Stations", "🚓", "Where police keep us safe"],
    ]],
    ["Community Helpers", [
      ["Doctor", "🧑‍⚕️", "Keeps us healthy"],
      ["Teacher", "👩‍🏫", "Helps us learn"],
      ["Police Officer", "👮", "Keeps us safe"],
      ["Firefighter", "🧑‍🚒", "Puts out fires"],
      ["Farmer", "🧑‍🌾", "Grows our food"],
      ["Postman", "📮", "Brings our letters"],
    ]],
    ["Transport", [
      ["Road, Rail, Air and Water Transport", "🚌", "Ways we travel"],
      ["Traffic Rules", "🚦", "Red, yellow and green lights"],
      ["Road Safety", "🦺", "Crossing the road safely"],
    ]],
    ["Festivals and Celebrations", [
      ["National Festivals", "🎆", "Independence Day, Republic Day, Gandhi Jayanti"],
      ["Religious and Cultural Festivals", "🪔", "Diwali, Eid, Christmas, Pongal and more"],
      ["Celebrating Together", "🎉", "Sharing joy with everyone"],
    ]],
    ["Our Country", [
      ["India", "🗺️", "Our country"],
      ["National Flag", "🏳️", "The tricolour and the Ashoka Chakra"],
      ["National Symbols", "🦚", "Tiger, peacock, lotus and more"],
      ["National Anthem", "🎶", "Jana Gana Mana"],
    ]],
  ],
  2: [
    ["Family and Relationships", [
      ["Family Responsibilities", "🧹", "How everyone helps at home"],
      ["Different Family Traditions", "🪔", "Customs families follow"],
      ["Caring for Others", "🤗", "Looking after elders and little ones"],
    ]],
    ["Our Community", [
      ["Rural and Urban Communities", "🏙️", "Life in villages and cities"],
      ["Community Services", "🚰", "Water, electricity and garbage collection"],
      ["Local Occupations", "🧑‍🔧", "Work people do near us"],
    ]],
    ["Places Around Us", [
      ["Market", "🛒", "Buying fruits, vegetables and more"],
      ["Hospital", "🏥", "Doctors, nurses and medicines"],
      ["School", "🏫", "Where we learn"],
      ["Bank", "🏦", "Keeping money safe"],
      ["Post Office", "📮", "Sending letters and parcels"],
      ["Police Station", "🚓", "Help when we are in trouble"],
    ]],
    ["Occupations", [
      ["Farmers", "🧑‍🌾", "Growing crops"],
      ["Teachers", "👩‍🏫", "Teaching children"],
      ["Doctors", "🧑‍⚕️", "Treating the sick"],
      ["Engineers", "👷", "Building roads, bridges and machines"],
      ["Shopkeepers", "🏪", "Selling things we need"],
      ["Artisans", "🏺", "Potters, weavers and carpenters"],
    ]],
    ["Transport and Communication", [
      ["Types of Transport", "🚆", "Land, water and air transport"],
      ["Public Transport", "🚌", "Buses, trains and metros we share"],
      ["Postal Services", "✉️", "How letters reach us"],
      ["Telephone", "☎️", "Talking to people far away"],
      ["Internet Basics", "💻", "Messages and video calls"],
    ]],
    ["Maps and Directions", [
      ["Near and Far", "📍", "How close or far things are"],
      ["Left and Right", "↔️", "Knowing our left and right"],
      ["North, South, East, West", "🧭", "The four directions"],
      ["Simple Maps", "🗺️", "Drawing a map of our room or school"],
      ["Map Symbols", "🔣", "Signs that show places on a map"],
    ]],
    ["Our Environment", [
      ["Natural and Human-made Things", "🌳", "Things from nature and things people make"],
      ["Clean Surroundings", "🧹", "Keeping our area clean"],
      ["Waste Management", "♻️", "Wet waste, dry waste and recycling"],
    ]],
    ["India", [
      ["States and Capitals", "🏛️", "An introduction to India's states"],
      ["National Symbols", "🦚", "Our national bird, animal, flower and more"],
      ["Important Places", "🕌", "Famous places in India"],
      ["Indian Diversity", "🤝", "Many languages, foods and festivals"],
    ]],
  ],
  3: [
    ["Our Earth", [
      ["Earth", "🌍", "Our home planet"],
      ["Land and Water", "🏝️", "How much of Earth is land and water"],
      ["Continents and Oceans", "🌐", "Seven continents and five oceans"],
      ["Globe", "🌏", "A model of the Earth"],
    ]],
    ["Maps", [
      ["Map Symbols", "🔣", "Signs and colours on a map"],
      ["Directions", "🧭", "Finding north, south, east and west"],
      ["Scale", "📏", "How big places are on a map"],
      ["Reading Simple Maps", "🗺️", "Finding places on a map"],
    ]],
    ["Physical Features", [
      ["Mountains", "🏔️", "High land with peaks"],
      ["Hills", "⛰️", "Low, rounded high land"],
      ["Plains", "🌾", "Flat, low land"],
      ["Plateaus", "🏜️", "High, flat land"],
      ["Deserts", "🐪", "Dry, sandy land"],
      ["Valleys", "🏞️", "Low land between hills"],
    ]],
    ["Rivers and Water Bodies", [
      ["Rivers", "🌊", "Flowing water from mountains to the sea"],
      ["Lakes", "🛶", "Water surrounded by land"],
      ["Seas", "⛵", "Large bodies of salt water"],
      ["Oceans", "🐋", "The biggest water bodies"],
      ["Importance of Water", "💧", "Why we need water"],
    ]],
    ["People and Communities", [
      ["Different Communities", "🤝", "People living together"],
      ["Languages", "🗣️", "Languages spoken in India"],
      ["Food", "🍛", "Food from different regions"],
      ["Clothing", "👘", "What people wear in different places"],
      ["Houses", "🏠", "Houses suited to the weather"],
      ["Traditions", "🪔", "Customs that families follow"],
    ]],
    ["Occupations", [
      ["Agriculture", "🚜", "Growing crops and raising animals"],
      ["Industry", "🏭", "Making things in factories"],
      ["Services", "🧑‍💼", "Jobs that help people"],
      ["Traditional Occupations", "🏺", "Pottery, weaving and handicrafts"],
    ]],
    ["Local Government", [
      ["Village", "🛖", "Life in a village"],
      ["Panchayat", "🏛️", "The village's own government"],
      ["Municipality", "🏙️", "The town or city government"],
      ["Community Services", "🚰", "Water, roads and lights for all"],
    ]],
    ["India's Culture", [
      ["Festivals", "🎆", "Festivals across India"],
      ["Dance", "💃", "Folk and classical dances"],
      ["Music", "🎵", "Songs and instruments of India"],
      ["Food", "🍲", "Dishes from every state"],
      ["Clothing", "🥻", "Sarees, dhotis, turbans and more"],
      ["Languages", "🗣️", "India's many languages"],
    ]],
    ["Early History", [
      ["Early Humans", "🔥", "How the first people lived"],
      ["Ancient Settlements", "🏘️", "When people began to farm and settle"],
      ["Introduction to Civilizations", "🏛️", "The first towns and cities"],
    ]],
    ["Natural Resources", [
      ["Water", "💧", "Using water wisely"],
      ["Soil", "🟫", "Why soil matters"],
      ["Forests", "🌲", "Gifts from forests"],
      ["Minerals", "💎", "Useful things from the Earth"],
    ]],
  ],
  4: [
    ["India: Location and Physical Features", [
      ["Location of India", "📍", "Where India is on the map"],
      ["States and Union Territories", "🗺️", "India's states and UTs"],
      ["Himalayas", "🏔️", "The great northern mountains"],
      ["Northern Plains", "🌾", "Fertile land of the big rivers"],
      ["Peninsular Plateau", "⛰️", "The old rocky plateau of the south"],
      ["Coastal Plains", "🏖️", "Land along the seas"],
      ["Islands", "🏝️", "Andaman, Nicobar and Lakshadweep"],
    ]],
    ["Rivers of India", [
      ["Major Rivers", "🌊", "Ganga, Yamuna, Godavari and more"],
      ["River Systems", "🏞️", "Rivers and their tributaries"],
      ["Importance of Rivers", "🚣", "Water, farming and travel"],
      ["River Conservation", "♻️", "Keeping our rivers clean"],
    ]],
    ["Climate and Weather", [
      ["Seasons", "🍂", "India's seasons through the year"],
      ["Monsoon", "🌧️", "The rainy season winds"],
      ["Different Climatic Regions", "🌡️", "Hot, cold, wet and dry places"],
    ]],
    ["Agriculture", [
      ["Crops", "🌾", "Rice, wheat, cotton and more"],
      ["Farming Methods", "🚜", "Old and new ways of farming"],
      ["Irrigation", "🚿", "Bringing water to fields"],
      ["Farmers' Role", "🧑‍🌾", "How farmers feed the nation"],
      ["Major Agricultural Regions", "🗺️", "Where our crops grow"],
    ]],
    ["Resources", [
      ["Natural Resources", "🌳", "Gifts of nature"],
      ["Renewable and Non-renewable Resources", "🔋", "Resources that last and those that run out"],
      ["Conservation", "♻️", "Saving resources for the future"],
    ]],
    ["Indian History", [
      ["Ancient India", "📜", "India long ago"],
      ["Indus Valley Civilization", "🏺", "Harappa and Mohenjo-daro"],
      ["Vedic Period", "📖", "The age of the Vedas"],
      ["Mauryan Empire", "🦁", "Chandragupta and Ashoka"],
      ["Gupta Period", "✨", "The golden age of India"],
    ]],
    ["Indian Heritage", [
      ["Monuments", "🕌", "Famous buildings of India"],
      ["Art", "🎨", "Paintings and crafts"],
      ["Architecture", "🛕", "Temples, forts and palaces"],
      ["Literature", "📚", "Great books and poems"],
      ["Classical Dances", "💃", "Bharatanatyam, Kathak, Kuchipudi and more"],
    ]],
    ["Government", [
      ["What Is Government?", "🏛️", "Why we need a government"],
      ["Local Government", "🏘️", "Panchayats and municipalities"],
      ["State Government", "🏢", "How a state is run"],
      ["Central Government", "🏛️", "An introduction to the Union government"],
    ]],
    ["Rights and Responsibilities", [
      ["Rules", "📏", "Why rules matter"],
      ["Duties", "✅", "Things we should do"],
      ["Being a Responsible Citizen", "🙋", "Helping our country"],
      ["Respecting Others", "🤝", "Treating everyone fairly"],
    ]],
    ["Economy and Occupations", [
      ["Agriculture", "🚜", "Farming in India"],
      ["Manufacturing", "🏭", "Making goods in factories"],
      ["Services", "🧑‍💼", "Banking, teaching, health and more"],
      ["Trade", "🚢", "Buying and selling goods"],
    ]],
  ],
  5: [
    ["Earth and Globe", [
      ["Continents", "🌍", "The seven continents"],
      ["Oceans", "🌊", "The five oceans"],
      ["Latitudes", "📏", "Lines running east to west"],
      ["Longitudes", "📐", "Lines running north to south"],
      ["Equator", "🌐", "The line around the middle of the Earth"],
      ["Hemispheres", "🌗", "The halves of the Earth"],
    ]],
    ["Landforms", [
      ["Mountains", "🏔️", "How mountains are formed"],
      ["Plateaus", "⛰️", "Raised flat lands"],
      ["Plains", "🌾", "Flat lands where people farm"],
      ["Deserts", "🐪", "Hot and cold deserts"],
      ["Valleys", "🏞️", "Lands carved by rivers"],
    ]],
    ["Climate", [
      ["Weather vs Climate", "🌦️", "Day-to-day weather and long-term climate"],
      ["Seasons", "🍂", "Why seasons change"],
      ["Monsoon", "🌧️", "How the monsoon brings rain"],
      ["Climate Zones", "🌡️", "Hot, temperate and cold zones"],
    ]],
    ["Natural Resources", [
      ["Forests", "🌲", "Forests and their uses"],
      ["Water", "💧", "Water resources"],
      ["Soil", "🟫", "Types of soil"],
      ["Minerals", "💎", "Iron, coal and other minerals"],
      ["Energy Resources", "⚡", "Coal, oil, sun and wind"],
      ["Conservation", "♻️", "Protecting our resources"],
    ]],
    ["Agriculture", [
      ["Types of Farming", "🚜", "Subsistence and commercial farming"],
      ["Major Crops", "🌾", "Food crops and cash crops"],
      ["Irrigation", "🚿", "Wells, canals and tanks"],
      ["Agricultural Regions", "🗺️", "Where crops are grown"],
      ["Food Security", "🍚", "Enough food for everyone"],
    ]],
    ["Population and Settlements", [
      ["Rural Settlements", "🛖", "Villages and village life"],
      ["Urban Settlements", "🏙️", "Towns and cities"],
      ["Population", "👪", "How many people live in a place"],
      ["Migration", "🧳", "Why people move"],
    ]],
    ["Transport and Communication", [
      ["Roads", "🛣️", "Highways and roads"],
      ["Railways", "🚆", "India's railway network"],
      ["Airways", "✈️", "Air travel"],
      ["Waterways", "🚢", "Ships and boats"],
      ["Internet", "💻", "Connecting the world"],
      ["Digital Communication", "📱", "Phones, email and messages"],
    ]],
    ["Ancient Indian Civilization", [
      ["Indus Valley Civilization", "🏺", "Planned cities of long ago"],
      ["Vedic Age", "📖", "Life in the Vedic times"],
      ["Mahajanapadas", "🏰", "The great kingdoms"],
    ]],
    ["Major Indian Empires", [
      ["Mauryan Empire", "🦁", "Chandragupta Maurya and Ashoka"],
      ["Gupta Empire", "✨", "The golden age"],
      ["Cholas and Other Regional Kingdoms", "⚓", "Powerful kingdoms of the south and beyond"],
    ]],
    ["Medieval India", [
      ["Major Kingdoms", "👑", "Kingdoms of medieval India"],
      ["Delhi Sultanate", "🕌", "Rulers of Delhi"],
      ["Mughal Empire", "🏰", "Babur to Aurangzeb"],
    ]],
    ["Indian Culture and Heritage", [
      ["Architecture", "🛕", "Temples, mosques, forts and palaces"],
      ["Literature", "📚", "Great writers and books"],
      ["Art", "🎨", "Paintings and crafts"],
      ["Music", "🎻", "Classical and folk music"],
      ["Dance", "💃", "Dances of India"],
      ["Languages", "🗣️", "India's languages and scripts"],
    ]],
    ["India's Freedom Movement", [
      ["British Rule", "⛓️", "How the British came to rule India"],
      ["Important Movements", "✊", "Non-cooperation, Salt March, Quit India"],
      ["Major Freedom Fighters", "🕊️", "Gandhi, Nehru, Bose, Bhagat Singh and more"],
      ["Independence", "🎆", "15 August 1947"],
    ]],
    ["Indian Government", [
      ["Constitution", "📜", "The basic idea of our Constitution"],
      ["Parliament", "🏛️", "Lok Sabha and Rajya Sabha"],
      ["President", "🎖️", "The head of our country"],
      ["Prime Minister", "🧑‍💼", "The head of the government"],
      ["State Government", "🏢", "Governor, Chief Minister and the state"],
      ["Local Government", "🏘️", "Panchayats and municipalities"],
    ]],
    ["Democracy", [
      ["Meaning of Democracy", "🗳️", "Government by the people"],
      ["Elections", "📋", "How we choose our leaders"],
      ["Voting", "☑️", "Every vote counts"],
      ["Representation", "🙋", "Leaders who speak for us"],
    ]],
    ["Rights and Duties", [
      ["Fundamental Rights", "⚖️", "Rights every citizen has"],
      ["Fundamental Duties", "✅", "Duties every citizen has"],
      ["Responsibilities of Citizens", "🙌", "How we help our nation"],
    ]],
    ["Diversity and Equality", [
      ["Unity in Diversity", "🤝", "Many people, one nation"],
      ["Different Cultures", "🎭", "Learning about each other"],
      ["Equality", "⚖️", "Everyone is equal"],
      ["Respect and Inclusion", "💛", "Making everyone feel welcome"],
    ]],
  ],
};
