import type { Subject } from "./subjects";
import { SOCIAL_SYLLABUS } from "./socialStudiesTopics";

export interface TopicModule {
  label: string;
  icon: string;
  topic: string;
  description: string;
  // Section heading on the topic screen, e.g. "Biology".
  group?: string;
}

const MATH_MODULES: TopicModule[] = [
  { label: "Addition", icon: "➕", topic: "Addition", description: "Practice adding numbers together" },
  { label: "Subtraction", icon: "➖", topic: "Subtraction", description: "Practice subtracting numbers" },
  { label: "Multiplication", icon: "✖️", topic: "Multiplication", description: "Practice multiplying numbers" },
  { label: "Division", icon: "➗", topic: "Division", description: "Practice dividing numbers" },
  { label: "Tables", icon: "🔢", topic: "Multiplication Tables", description: "Practice multiplication tables" },
  { label: "Areas", icon: "📐", topic: "Area and Perimeter", description: "Practice area and perimeter" },
];

const MATH_ALL_TOPICS: TopicModule = {
  label: "All Topics (Mixed Review)",
  icon: "🧮",
  description: "A mixed review covering every topic above",
  topic:
    "Mixed Review: Addition, Subtraction, Multiplication, Division, Multiplication Tables, and Area and Perimeter",
};

const SCIENCE_MODULES: TopicModule[] = [
  { label: "Plants", icon: "🌱", topic: "Plants", description: "Learn about plants and how they grow" },
  { label: "Animals", icon: "🐾", topic: "Animals", description: "Learn about animals and their homes" },
  { label: "Human Body", icon: "🧍", topic: "Human Body", description: "Learn about our body and its parts" },
  { label: "Our Earth", icon: "🌍", topic: "Our Earth, Water, and Air", description: "Learn about the Earth, water, and air" },
  { label: "Food & Health", icon: "🍎", topic: "Food and Health", description: "Learn about healthy food and habits" },
  { label: "Matter & Force", icon: "⚙️", topic: "Matter and Force", description: "Learn about materials, force, and simple machines" },
];

const SCIENCE_ALL_TOPICS: TopicModule = {
  label: "All Topics (Mixed Review)",
  icon: "🧪",
  description: "A mixed review covering every topic above",
  topic:
    "Mixed Review: Plants, Animals, Human Body, Our Earth Water and Air, Food and Health, and Matter and Force",
};

// Topics for each grade, following the usual primary-school syllabus
// (NCERT / CBSE-style). The topics that match the modules above reuse them
// exactly, so they keep their instant question bank, intro and videos; the
// rest are generated by the AI like a typed-in topic.
const m = (label: string, icon: string, description: string, topic = label): TopicModule => ({
  label,
  icon,
  topic,
  description,
});

const [ADD, SUB, MUL, DIV, TABLES, AREA] = MATH_MODULES;
const [PLANTS, ANIMALS, BODY, EARTH, FOOD] = SCIENCE_MODULES;

// Puts a list of topics under one section heading.
const section = (group: string, modules: TopicModule[]): TopicModule[] => modules.map((module) => ({ ...module, group }));
// A grade-specific name for one of the modules above, keeping its topic (and
// so its instant questions, introduction and videos).
const as = (module: TopicModule, label: string, description: string): TopicModule => ({ ...module, label, description });

// Grades 1–5 Mathematics, following the school syllabus.
const MATH_BY_GRADE: Record<number, TopicModule[]> = {
  1: [
    m("Counting 1 to 100", "🔢", "Count forwards and backwards up to 100"),
    m("Number Names", "🔤", "Read and write numbers in words"),
    m("Place Value: Ones and Tens", "🔟", "How many tens and ones make a number"),
    m("Comparing Numbers", "⚖️", "Bigger, smaller and equal: >, < and ="),
    as(ADD, "Addition", "Putting numbers together"),
    as(SUB, "Subtraction", "Taking away and finding what is left"),
    m("Shapes", "🔺", "Circles, squares, triangles and rectangles"),
    m("Patterns", "🔁", "Find what comes next in a pattern"),
    m("Measurement: Long and Short, Heavy and Light", "📏", "Compare lengths and weights"),
    m("Time: Days and the Clock", "🕒", "Morning, night, days of the week and o'clock"),
    m("Money: Coins and Notes", "🪙", "Know our coins and notes and count money"),
    m("Picture Data", "📊", "Read simple picture charts"),
  ],
  2: [
    m("Numbers up to 1,000", "🔢", "Read, write and order 3-digit numbers"),
    m("Place Value: Hundreds, Tens and Ones", "🔟", "What each digit in a number is worth"),
    as(ADD, "Addition with Carrying", "Adding with regrouping"),
    as(SUB, "Subtraction with Borrowing", "Subtracting with regrouping"),
    m("Introduction to Multiplication", "✖️", "Multiplication as repeated addition"),
    m("Introduction to Division", "➗", "Sharing equally and making groups"),
    m("Fractions: Half and Quarter", "🍕", "Equal parts of a whole"),
    m("2D and 3D Shapes", "🧊", "Properties of flat and solid shapes"),
    m("Measurement: Length, Weight and Capacity", "⚖️", "Measure using cm, kg and litres"),
    m("Time: Reading Clocks", "🕒", "Hours, half hours and quarter hours"),
    m("Money: Calculating Amounts", "💰", "Add money and find the change"),
    m("Graphs and Pictographs", "📊", "Read and make simple graphs"),
  ],
  3: [
    m("Numbers up to 10,000", "🔢", "Place value, comparing and ordering 4-digit numbers"),
    TABLES,
    as(MUL, "Multiplication", "Multiplying 2- and 3-digit numbers"),
    as(DIV, "Division", "Dividing with and without remainders"),
    m("Fractions", "🍕", "Parts of a whole and parts of a group"),
    m("Introduction to Decimals", "🔸", "Tenths and money with decimals"),
    as(AREA, "Perimeter and Area", "Perimeter, and an introduction to area"),
    m("Angles", "📐", "Right angles, and angles bigger or smaller"),
    m("Measurement", "📏", "Length, weight and capacity"),
    m("Time and Calendar", "🗓️", "Clock time, days, weeks and months"),
    m("Money", "💵", "Rupees and paise, bills and change"),
    m("Pictographs and Bar Graphs", "📊", "Read and draw pictographs and bar graphs"),
  ],
  4: [
    m("Large Numbers and Place Value", "🔢", "Numbers up to 1 lakh and the place value chart"),
    as(ADD, "Addition of Large Numbers", "Adding 4- and 5-digit numbers"),
    as(SUB, "Subtraction of Large Numbers", "Subtracting 4- and 5-digit numbers"),
    as(MUL, "Multi-digit Multiplication", "Multiplying by 2- and 3-digit numbers"),
    as(DIV, "Long Division", "Dividing step by step"),
    m("Factors and Multiples", "🧩", "Factors, multiples and divisibility"),
    m("Fractions", "🍕", "Comparing and ordering fractions"),
    m("Equivalent Fractions", "🟰", "Different fractions that are the same amount"),
    m("Decimals", "🔸", "Tenths and hundredths"),
    m("Geometry: Lines and Shapes", "📐", "Lines, rays, line segments and shapes"),
    m("Angles", "📐", "Acute, right and obtuse angles"),
    as(AREA, "Perimeter and Area", "Perimeter and area of rectangles and squares"),
    m("Measurement Conversions", "🔄", "km, m, cm · kg, g · L, mL"),
    m("Data Handling", "📊", "Bar graphs and data interpretation"),
  ],
  5: [
    m("Large Numbers and Place Value", "🔢", "Numbers up to crores, Indian and international systems"),
    as(MUL, "Multi-digit Multiplication", "Multiplying large numbers"),
    as(DIV, "Long Division", "Dividing large numbers"),
    m("Factors and Multiples", "🧩", "Factors, multiples, HCF and LCM"),
    m("Prime Numbers", "🔐", "Prime and composite numbers"),
    m("Fractions", "🍕", "Add, subtract and multiply fractions"),
    m("Decimals", "🔸", "Operations with decimals"),
    m("Introduction to Percentages", "💯", "What percent means and simple percentages"),
    m("Ratio Basics", "⚖️", "Comparing quantities with ratios"),
    m("Geometry", "📐", "Triangles, quadrilaterals, circles and angles"),
    m("Area and Volume", "📦", "Area of shapes and volume of cubes and cuboids"),
    m("Coordinate Basics", "📍", "Locating points on a grid"),
    m("Patterns", "🔁", "Number and shape patterns"),
    m("Data Interpretation", "📊", "Tables, bar graphs and averages"),
    m("Word Problems", "🧠", "Multi-step word problems"),
    m("Logical Reasoning", "🤔", "Puzzles and mathematical patterns"),
  ],
};

// Grades 1–5 Science, following the school syllabus.
const SCIENCE_BY_GRADE: Record<number, TopicModule[]> = {
  1: [
    ...section("Living World", [
      m("Living and Non-living Things", "🐞", "What makes something alive"),
      as(PLANTS, "Plants", "Plants around us and how they grow"),
      as(ANIMALS, "Animals", "Animals around us"),
      as(BODY, "Human Body", "Parts of our body"),
      m("Five Senses", "👀", "See, hear, smell, taste and touch"),
    ]),
    ...section("Environment", [
      m("Air", "🌬️", "Air is all around us"),
      m("Water", "💧", "Uses of water and saving water"),
      m("Weather", "🌦️", "Sunny, rainy, windy and cloudy days"),
      m("Seasons", "🍂", "Summer, rainy season and winter"),
      m("Day and Night", "🌗", "The Sun by day, the Moon and stars by night"),
    ]),
    ...section("Everyday Science", [
      as(FOOD, "Food", "Food we eat and where it comes from"),
      m("Cleanliness", "🧼", "Keeping ourselves and our homes clean"),
      m("Healthy Habits", "🪥", "Good habits for a healthy body"),
      m("Safety", "🚦", "Staying safe at home, school and on the road"),
      m("Different Materials", "🧱", "Wood, paper, plastic, metal and cloth"),
    ]),
  ],
  2: [
    ...section("Plants", [
      m("Roots", "🥕", "How roots hold the plant and take in water"),
      m("Stem", "🌿", "How the stem holds up the plant and carries water"),
      m("Leaves", "🍃", "How leaves make food for the plant"),
      m("Flowers", "🌸", "Flowers and their colours"),
      m("Fruits and Seeds", "🍎", "Fruits, seeds and new plants"),
      m("What Plants Need to Grow", "☀️", "Sunlight, water, air and soil"),
    ]),
    ...section("Animals", [
      m("Domestic and Wild Animals", "🐄", "Animals at home and in the wild"),
      m("Animal Homes", "🏠", "Where animals live"),
      m("Food Habits of Animals", "🥩", "Plant-eaters, meat-eaters and both"),
      m("Animal Body Parts", "🦒", "Body parts that help animals live"),
    ]),
    ...section("Human Body", [
      m("Major Body Parts", "🧍", "Head, trunk, arms and legs"),
      m("Sense Organs", "👂", "Eyes, ears, nose, tongue and skin"),
      m("Healthy Food and Food Groups", "🥗", "Energy, body-building and protective foods"),
      m("Exercise and Hygiene", "🏃", "Staying fit and clean"),
    ]),
    ...section("Physical Science", [
      m("Hard and Soft Materials", "🪨", "Which things are hard and which are soft"),
      m("Rough and Smooth", "🧽", "Feeling different surfaces"),
      m("Solids and Liquids", "🧊", "Things that keep their shape and things that flow"),
      m("Push and Pull", "🛒", "Forces that make things move"),
      m("Light and Shadows", "🔦", "Sources of light and how shadows form"),
    ]),
    ...section("Our Surroundings", [
      m("Water and Air", "💧", "Why we need water and air"),
      m("Weather and Seasons", "🌦️", "Seasons and the clothes we wear"),
    ]),
  ],
  3: [
    ...section("Biology", [
      m("Plant Life Cycle", "🌱", "From seed to plant to seed"),
      m("Animal Life Cycle", "🦋", "How animals grow and change"),
      m("Animal Classification", "🐾", "Grouping animals: mammals, birds, fish and more"),
      m("Habitats", "🏞️", "Where plants and animals live"),
      m("Adaptations", "🐪", "How living things suit their homes"),
      m("Food Chains: Introduction", "🔗", "Who eats whom"),
    ]),
    ...section("Human Body", [
      m("Digestive System: Introduction", "🍽️", "How our body uses food"),
      m("Bones and Muscles", "🦴", "How we stand and move"),
      m("Teeth", "🦷", "Types of teeth and caring for them"),
      m("Healthy Diet", "🥗", "Eating a balanced diet"),
    ]),
    ...section("Physical Science", [
      m("Solids, Liquids and Gases", "🧊", "The three states of matter"),
      m("Force and Motion", "⚽", "Push, pull and how things move"),
      m("Light and Shadows", "🔦", "How light travels and shadows form"),
      m("Sound", "🔊", "How sounds are made and heard"),
      m("Heat", "🔥", "Hot and cold, and how heat moves"),
    ]),
    ...section("Earth Science", [
      as(EARTH, "The Earth", "Land, water and air on our planet"),
      m("Sun and Moon", "🌞", "Our Sun and the Moon"),
      m("Weather", "🌦️", "Kinds of weather and measuring it"),
      m("Water Cycle: Introduction", "🌧️", "How water goes round and round"),
      m("Natural Resources", "🌳", "Gifts from nature and using them wisely"),
    ]),
  ],
  4: [
    ...section("Biology", [
      m("Plant Reproduction", "🌸", "How plants make new plants"),
      m("Seeds and Germination", "🌱", "How seeds spread and sprout"),
      m("Animal Adaptations", "🐪", "How animals suit their habitats"),
      m("Ecosystems", "🏞️", "Living and non-living things working together"),
      m("Food Chains", "🔗", "Producers, consumers and decomposers"),
    ]),
    ...section("Human Body", [
      m("Digestive System", "🍽️", "The journey of food in our body"),
      m("Respiratory System", "🫁", "How we breathe"),
      m("Circulatory System", "🫀", "The heart and blood"),
      m("Skeletal System", "🦴", "Our bones and joints"),
      m("Muscular System", "💪", "How muscles help us move"),
    ]),
    ...section("Physics", [
      m("Force", "👐", "Pushes, pulls and their effects"),
      m("Motion", "🚲", "Kinds of motion"),
      m("Gravity", "🍎", "Why things fall down"),
      m("Energy", "⚡", "Forms of energy around us"),
      m("Light", "💡", "Reflection and how we see"),
      m("Sound", "🔊", "Vibrations, pitch and loudness"),
      m("Electricity", "🔌", "Uses of electricity and staying safe"),
      m("Magnets", "🧲", "Magnetic poles, attraction and repulsion"),
      m("Matter and Its Changes", "🧪", "Melting, freezing and evaporation"),
    ]),
    ...section("Earth Science", [
      m("Rocks", "🪨", "Kinds of rocks and how they form"),
      m("Soil", "🟫", "Layers and types of soil"),
      m("The Water Cycle", "🌧️", "Evaporation, condensation and rain"),
      m("Natural Resources", "🌳", "Renewable and non-renewable resources"),
      m("Pollution", "🏭", "Air, water and land pollution"),
      m("Conservation", "♻️", "Saving water, forests and energy"),
    ]),
  ],
  5: [
    ...section("Biology", [
      m("Cells: Introduction", "🔬", "The building blocks of living things"),
      m("Plant and Animal Cells", "🧫", "How plant and animal cells differ"),
      m("Life Cycles", "🐸", "Life cycles of plants and animals"),
      m("Reproduction", "🐣", "How living things make young ones"),
      m("Ecosystems", "🏞️", "How living things depend on each other"),
      m("Food Chains and Food Webs", "🕸️", "How energy flows in nature"),
      m("Adaptations", "🐧", "Special features for survival"),
      m("Biodiversity", "🦜", "The variety of life on Earth"),
    ]),
    ...section("Human Body", [
      m("Digestive System", "🍽️", "Organs of digestion and what they do"),
      m("Respiratory System", "🫁", "Lungs and breathing"),
      m("Circulatory System", "🫀", "Heart, blood and blood vessels"),
      m("Nervous System", "🧠", "The brain, spinal cord and nerves"),
      m("Skeletal and Muscular Systems", "🦴", "Bones, joints and muscles"),
      m("Healthy Lifestyle", "🏃", "Food, exercise, sleep and hygiene"),
    ]),
    ...section("Physics", [
      m("Force and Motion", "⚽", "How forces change motion"),
      m("Gravity", "🍎", "The pull of the Earth"),
      m("Friction", "🛷", "The force that slows things down"),
      m("Forms of Energy", "⚡", "Heat, light, sound, electrical and more"),
      m("Light", "💡", "Reflection, refraction and shadows"),
      m("Sound", "🔊", "How sound travels"),
      m("Electricity", "🔌", "Conductors, insulators and safety"),
      m("Simple Circuits", "🔋", "Cells, wires, switches and bulbs"),
      m("Magnetism", "🧲", "Magnets and magnetic materials"),
    ]),
    ...section("Chemistry", [
      m("States of Matter", "🧊", "Solids, liquids, gases and changing states"),
      m("Properties of Materials", "🧱", "Hard, soft, transparent, waterproof and more"),
      m("Physical Changes", "✂️", "Changes that can be undone"),
      m("Chemical Changes: Introduction", "🔥", "Changes that make new substances"),
      m("Mixtures and Solutions", "🥤", "Mixing, dissolving and separating"),
    ]),
    ...section("Earth and Space", [
      m("The Solar System", "🪐", "The Sun, planets and their order"),
      m("Earth and Moon", "🌍", "How the Earth and Moon move"),
      m("Day and Night", "🌗", "Why we have day and night"),
      m("Seasons", "🍂", "Why the seasons change"),
      m("Rocks and Minerals", "💎", "Kinds of rocks and useful minerals"),
      m("Water Cycle", "🌧️", "How water moves around the Earth"),
      m("Natural Resources", "🌳", "Using and saving resources"),
      m("Climate and Environment", "🌎", "Climate, pollution and protecting our planet"),
    ]),
  ],
};

// Grades 1–5 Social Studies (socialStudiesTopics.ts): each syllabus item is a
// topic named "Chapter: Item", shown as "Item" under its chapter heading.
const SOCIAL_BY_GRADE: Record<number, TopicModule[]> = Object.fromEntries(
  Object.entries(SOCIAL_SYLLABUS).map(([grade, chapters]) => [
    Number(grade),
    chapters.flatMap(([chapter, items]) =>
      section(chapter, items.map(([item, icon, description]) => m(item, icon, description, `${chapter}: ${item}`))),
    ),
  ]),
);

// The chapters most grades build on, used when no grade is chosen.
const SOCIAL_MODULES: TopicModule[] = [
  m("My Family", "👨‍👩‍👧‍👦", "Family members and relationships"),
  m("Community Helpers", "🧑‍🚒", "People who help us"),
  m("Transport and Communication", "🚌", "How we travel and send messages"),
  m("Maps and Directions", "🧭", "Reading maps and finding directions"),
  m("Our Earth", "🌍", "Land, water, continents and oceans"),
  m("Government and Democracy", "🏛️", "How our country is run"),
];

const SOCIAL_ALL_TOPICS: TopicModule = {
  label: "All Topics (Mixed Review)",
  icon: "🌏",
  description: "A mixed review covering every chapter above",
  topic: "Mixed Review: Family, Community Helpers, Transport, Maps and Directions, Our Earth, India and Government",
};

export const GRADES = [1, 2, 3, 4, 5];

const BY_GRADE: Record<Subject, Record<number, TopicModule[]>> = {
  Mathematics: MATH_BY_GRADE,
  Science: SCIENCE_BY_GRADE,
  "Social Studies": SOCIAL_BY_GRADE,
};
const MODULES: Record<Subject, TopicModule[]> = { Mathematics: MATH_MODULES, Science: SCIENCE_MODULES, "Social Studies": SOCIAL_MODULES };
const ALL_TOPICS: Record<Subject, TopicModule> = { Mathematics: MATH_ALL_TOPICS, Science: SCIENCE_ALL_TOPICS, "Social Studies": SOCIAL_ALL_TOPICS };

export function getGradeTopicModules(subject: Subject, grade: number): TopicModule[] {
  return BY_GRADE[subject][grade] ?? getTopicModules(subject);
}

export function getTopicModules(subject: Subject): TopicModule[] {
  return MODULES[subject];
}

export function getAllTopicsModule(subject: Subject): TopicModule {
  return ALL_TOPICS[subject];
}

// Which subject a finished test's topic belongs to. Custom typed-in topics
// aren't in any list, so they count as Mathematics unless the test itself
// recorded its subject.
export function subjectForTopic(topic: string): Subject {
  for (const subject of ["Social Studies", "Science", "Mathematics"] as Subject[]) {
    if (ALL_TOPICS[subject].topic === topic || MODULES[subject].some((m) => m.topic === topic)) return subject;
  }
  if (Object.values(MATH_BY_GRADE).some((list) => list.some((m) => m.topic === topic))) return "Mathematics";
  if (Object.values(SCIENCE_BY_GRADE).some((list) => list.some((m) => m.topic === topic))) return "Science";
  if (Object.values(SOCIAL_BY_GRADE).some((list) => list.some((m) => m.topic === topic))) return "Social Studies";
  return "Mathematics";
}

// Mixed reviews have a long topic listing every module — shorten it for display.
export function displayTopic(topic: string): string {
  if (topic === MATH_ALL_TOPICS.topic) return "Mixed Review (Maths)";
  if (topic === SCIENCE_ALL_TOPICS.topic) return "Mixed Review (Science)";
  if (topic === SOCIAL_ALL_TOPICS.topic) return "Mixed Review (Social Studies)";
  return topic;
}
