import type { Subject } from "./components/SubjectSelect";

export interface TopicModule {
  label: string;
  icon: string;
  topic: string;
  description: string;
}

const MATH_MODULES: TopicModule[] = [
  { label: "Addition", icon: "➕", topic: "Addition", description: "Practice adding numbers together" },
  { label: "Subtraction", icon: "➖", topic: "Subtraction", description: "Practice subtracting numbers" },
  { label: "Multiplication", icon: "✖️", topic: "Multiplication", description: "Practice multiplying numbers" },
  { label: "Division", icon: "➗", topic: "Division", description: "Practice dividing numbers" },
  { label: "Tables", icon: "🔢", topic: "Multiplication Tables", description: "Practice multiplication tables" },
  { label: "Areas", icon: "📐", topic: "Area and Perimeter", description: "Practice area and perimeter" },
];

const MATH_ALL_TOPICS: TopicModule = {
  label: "All Topics (Mixed Review)",
  icon: "🧮",
  description: "A mixed review covering every topic above",
  topic:
    "Mixed Review: Addition, Subtraction, Multiplication, Division, Multiplication Tables, and Area and Perimeter",
};

const SCIENCE_MODULES: TopicModule[] = [
  { label: "Plants", icon: "🌱", topic: "Plants", description: "Learn about plants and how they grow" },
  { label: "Animals", icon: "🐾", topic: "Animals", description: "Learn about animals and their homes" },
  { label: "Human Body", icon: "🧍", topic: "Human Body", description: "Learn about our body and its parts" },
  { label: "Our Earth", icon: "🌍", topic: "Our Earth, Water, and Air", description: "Learn about the Earth, water, and air" },
  { label: "Food & Health", icon: "🍎", topic: "Food and Health", description: "Learn about healthy food and habits" },
  { label: "Matter & Force", icon: "⚙️", topic: "Matter and Force", description: "Learn about materials, force, and simple machines" },
];

const SCIENCE_ALL_TOPICS: TopicModule = {
  label: "All Topics (Mixed Review)",
  icon: "🧪",
  description: "A mixed review covering every topic above",
  topic:
    "Mixed Review: Plants, Animals, Human Body, Our Earth Water and Air, Food and Health, and Matter and Force",
};

// Topics for each grade, following the usual primary-school syllabus
// (NCERT / CBSE-style). The topics that match the modules above reuse them
// exactly, so they keep their instant question bank, intro and videos; the
// rest are generated by the AI like a typed-in topic.
const m = (label: string, icon: string, description: string, topic = label): TopicModule => ({
  label,
  icon,
  topic,
  description,
});

const [ADD, SUB, MUL, DIV, TABLES, AREA] = MATH_MODULES;
const [PLANTS, ANIMALS, BODY, EARTH, FOOD, MATTER] = SCIENCE_MODULES;

const MATH_BY_GRADE: Record<number, TopicModule[]> = {
  1: [
    m("Numbers 1 to 100", "🔢", "Count, read and write numbers up to 100"),
    ADD,
    SUB,
    m("Shapes Around Us", "🔺", "Circles, squares, triangles and rectangles"),
    m("Patterns", "🔁", "Find what comes next in a pattern"),
    m("Long and Short, Heavy and Light", "📏", "Compare sizes and weights"),
    m("Days, Months and Time", "📅", "Days of the week, months and telling time"),
    m("Money: Coins and Notes", "🪙", "Know our coins and notes and count money"),
  ],
  2: [
    m("Place Value: Tens and Ones", "🔟", "Numbers up to 1000 and their place value"),
    ADD,
    SUB,
    m("Introduction to Multiplication", "✖️", "Multiplication as repeated addition"),
    m("2D and 3D Shapes", "🧊", "Flat shapes and solid shapes"),
    m("Measurement: Length, Weight and Capacity", "⚖️", "Measure using cm, kg and litres"),
    m("Telling Time on a Clock", "🕒", "Read hours and half hours on a clock"),
    m("Money: Adding and Spending", "💰", "Add money and find the change"),
    m("Patterns", "🔁", "Number and shape patterns"),
  ],
  3: [
    m("Numbers up to 1000", "🔢", "Read, write, compare and order 3-digit numbers"),
    ADD,
    SUB,
    MUL,
    DIV,
    TABLES,
    m("Fractions: Half, Quarter and Three-Quarters", "🍕", "Parts of a whole"),
    m("Time and Calendar", "🗓️", "Clock time, days, weeks and months"),
    m("Money", "💵", "Rupees and paise, bills and change"),
    m("Measurement", "📏", "Length, weight and capacity"),
    m("Data Handling", "📊", "Read and make simple tally charts and pictographs"),
  ],
  4: [
    m("Large Numbers up to 10,000", "🔢", "Place value and comparing 4- and 5-digit numbers"),
    MUL,
    DIV,
    TABLES,
    m("Fractions", "🍕", "Equivalent fractions and comparing fractions"),
    AREA,
    m("Time: Hours, Minutes and Seconds", "⏱️", "Converting and calculating time"),
    m("Money and Bills", "🧾", "Making bills and solving money problems"),
    m("Geometry: Lines and Angles", "📐", "Lines, rays, angles and shapes"),
    m("Patterns and Symmetry", "🦋", "Symmetry and number patterns"),
    m("Data Handling", "📊", "Bar graphs and pictographs"),
  ],
  5: [
    m("Large Numbers and Place Value", "🔢", "Numbers up to lakhs and the place value chart"),
    MUL,
    DIV,
    m("Factors and Multiples", "🧩", "Factors, multiples, HCF and LCM"),
    m("Fractions", "🍕", "Add, subtract and compare fractions"),
    m("Decimals", "🔸", "Tenths, hundredths and decimal money"),
    AREA,
    m("Volume", "📦", "Measure the space inside cubes and cuboids"),
    m("Angles", "📐", "Measure and name angles"),
    m("Percentage", "💯", "What percent means and simple percentages"),
    m("Data Handling", "📊", "Bar graphs, tables and averages"),
  ],
};

const SCIENCE_BY_GRADE: Record<number, TopicModule[]> = {
  1: [
    m("My Body", "🧍", "Parts of our body and what they do"),
    m("Our Senses", "👀", "See, hear, smell, taste and touch"),
    m("Plants Around Us", "🌱", "Trees, shrubs, herbs and flowers"),
    m("Animals Around Us", "🐾", "Pet, farm and wild animals"),
    m("Food We Eat", "🍎", "Healthy foods and where food comes from"),
    m("Keeping Clean", "🧼", "Good habits to stay clean and healthy"),
    m("Water", "💧", "Uses of water and saving water"),
    m("Weather and Seasons", "🌦️", "Sunny, rainy, windy and cold days"),
  ],
  2: [
    m("Parts of a Plant", "🌿", "Roots, stem, leaves, flowers and fruits"),
    m("Animals and Their Homes", "🏠", "Where animals live"),
    m("Our Senses", "👂", "Our five sense organs"),
    FOOD,
    m("Water and Its Uses", "💧", "Where we get water and how we use it"),
    m("Air Around Us", "🌬️", "Air is everywhere and we need it"),
    m("Weather and Seasons", "🌦️", "Seasons and the clothes we wear"),
    m("Safety Rules", "🚦", "Staying safe at home, school and on the road"),
  ],
  3: [
    PLANTS,
    ANIMALS,
    BODY,
    FOOD,
    EARTH,
    m("Birds", "🐦", "Beaks, claws, feathers and nests"),
    m("Soil", "🪨", "Types of soil and why soil matters"),
    m("Light and Shadows", "🔦", "Sources of light and how shadows form"),
  ],
  4: [
    m("Plants: Parts and Their Functions", "🌿", "How roots, stems and leaves help a plant"),
    m("Animal Adaptations", "🐪", "How animals suit their habitats"),
    m("Teeth and Digestion", "🦷", "Our teeth and the digestive system"),
    FOOD,
    m("Solids, Liquids and Gases", "🧊", "The three states of matter"),
    m("The Water Cycle", "🌧️", "Evaporation, clouds and rain"),
    m("Force, Work and Simple Machines", "⚙️", "Push, pull and machines that help us"),
    m("Our Environment", "🌳", "Living and non-living things and caring for nature"),
  ],
  5: [
    m("Human Body Systems", "🫀", "Skeleton, muscles, heart, lungs and brain"),
    m("Seeds and Germination", "🌱", "How seeds spread and grow into plants"),
    ANIMALS,
    m("Food and Nutrition", "🥗", "Nutrients, balanced diet and deficiency diseases"),
    MATTER,
    m("The Solar System", "🪐", "The Sun, planets, Moon and stars"),
    EARTH,
    m("Natural Resources and Conservation", "♻️", "Saving water, forests and energy"),
    m("Diseases and Hygiene", "🩺", "Germs, how diseases spread and staying healthy"),
  ],
};

export const GRADES = [1, 2, 3, 4, 5];

export function getGradeTopicModules(subject: Subject, grade: number): TopicModule[] {
  const table = subject === "Science" ? SCIENCE_BY_GRADE : MATH_BY_GRADE;
  return table[grade] ?? getTopicModules(subject);
}

export function getTopicModules(subject: Subject): TopicModule[] {
  return subject === "Science" ? SCIENCE_MODULES : MATH_MODULES;
}

export function getAllTopicsModule(subject: Subject): TopicModule {
  return subject === "Science" ? SCIENCE_ALL_TOPICS : MATH_ALL_TOPICS;
}

// Which subject a finished test's topic belongs to. Custom typed-in topics
// aren't in either list, so they count as Mathematics unless the test itself
// recorded its subject.
export function subjectForTopic(topic: string): Subject {
  if (topic === SCIENCE_ALL_TOPICS.topic || SCIENCE_MODULES.some((m) => m.topic === topic)) return "Science";
  const isMath = Object.values(MATH_BY_GRADE).some((list) => list.some((m) => m.topic === topic));
  if (!isMath && Object.values(SCIENCE_BY_GRADE).some((list) => list.some((m) => m.topic === topic))) {
    return "Science";
  }
  return "Mathematics";
}

// Mixed reviews have a long topic listing every module — shorten it for display.
export function displayTopic(topic: string): string {
  if (topic === MATH_ALL_TOPICS.topic) return "Mixed Review (Maths)";
  if (topic === SCIENCE_ALL_TOPICS.topic) return "Mixed Review (Science)";
  return topic;
}
